import ReactNative from 'react-native';
const { StyleSheet, Platform } = ReactNative;
import { ThemeColors } from './context/ThemeContext';

export const createGlobalStyles = (theme: ThemeColors) => StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: theme.background,
    },
    flex1: {
        flex: 1,
    },
    screenContainer: {
        flex: 1,
        backgroundColor: theme.background,
    },
    scrollContent: {
        padding: 20,
        paddingBottom: 120,
    },
    // Header
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        paddingVertical: 20,
        borderBottomWidth: 1,
        borderBottomColor: theme.border,
        minHeight: 64,
    },
    headerTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: theme.text,
        letterSpacing: 3,
    },
    // Section
    sectionTitle: {
        fontSize: 13,
        fontWeight: '600',
        color: theme.text,
        letterSpacing: 2,
    },
    // Mission Card
    missionCard: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: theme.surface,
        borderRadius: 20,
        padding: 20,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: theme.border,
        minHeight: 88,
    },
    missionIconBox: {
        width: 56,
        height: 56,
        borderRadius: 18,
        backgroundColor: 'rgba(19, 73, 236, 0.1)',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 18,
    },
    missionInfo: {
        flex: 1,
    },
    missionTitle: {
        fontSize: 15,
        fontWeight: '800',
        color: theme.text,
        marginBottom: 8,
        letterSpacing: 0.3,
    },
    missionTime: {
        fontSize: 13,
        color: theme.textSecondary,
        fontWeight: '500',
    },
    missionReward: {
        fontSize: 20,
        fontWeight: '900',
        color: theme.primary,
        marginLeft: 12,
    },
    // Judge Card
    judgeCard: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: theme.surface,
        borderRadius: 20,
        padding: 20,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: theme.border,
        minHeight: 88,
    },
    judgeIconBox: {
        width: 56,
        height: 56,
        borderRadius: 18,
        backgroundColor: 'rgba(19, 73, 236, 0.15)',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 18,
    },
    judgeInfo: {
        flex: 1,
    },
    judgeTitle: {
        fontSize: 15,
        fontWeight: '700',
        color: theme.text,
        marginBottom: 6,
        letterSpacing: 0.2,
    },
    judgeSubtitle: {
        fontSize: 13,
        color: theme.textSecondary,
        fontWeight: '500',
    },
    judgeReward: {
        alignItems: 'flex-end',
        marginLeft: 12,
    },
    judgeRewardValue: {
        fontSize: 18,
        fontWeight: '700',
        color: theme.primary,
        marginBottom: 4,
    },
});

export const createCaptureStyles = (theme: ThemeColors) => StyleSheet.create({
    heroTitle: {
        fontSize: 32,
        fontWeight: '700',
        color: theme.text,
        lineHeight: 40,
        marginBottom: 12,
    },
    heroSubtitle: {
        fontSize: 16,
        color: theme.textSecondary,
        lineHeight: 24,
    },
    infoBox: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        backgroundColor: theme.surface,
        borderRadius: 16,
        padding: 16,
        marginBottom: 24,
        borderWidth: 1,
        borderColor: theme.border,
        gap: 12,
    },
    optionCard: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: theme.surface,
        borderRadius: 20,
        padding: 20,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: theme.border,
    },
    optionIconBox: {
        width: 64,
        height: 64,
        borderRadius: 20,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 16,
    },
    optionInfo: {
        flex: 1,
    },
    optionTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: theme.text,
        marginBottom: 4,
    },
    optionSubtitle: {
        fontSize: 13,
        color: theme.textSecondary,
        marginBottom: 6,
    },
    optionReward: {
        fontSize: 14,
        fontWeight: '600',
        color: theme.success,
    },
    promptCard: {
        backgroundColor: theme.surface,
        borderRadius: 24,
        padding: 24,
        borderWidth: 1,
        borderColor: theme.border,
    },
    promptBadge: {
        alignSelf: 'flex-start',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 8,
        marginBottom: 16,
    },
    promptBadgeText: {
        fontSize: 11,
        fontWeight: '700',
        letterSpacing: 1,
    },
    promptText: {
        fontSize: 22,
        fontWeight: '600',
        color: theme.text,
        lineHeight: 30,
        marginBottom: 12,
    },
    promptHint: {
        fontSize: 13,
        color: theme.textSecondary,
    },
    recordButton: {
        width: 100,
        height: 100,
        borderRadius: 50,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 8,
    },
    translationInput: {
        borderRadius: 16,
        padding: 16,
        fontSize: 14,
        minHeight: 100,
        textAlignVertical: 'top',
        borderWidth: 1,
    },
    submitButton: {
        borderRadius: 16,
        paddingVertical: 18,
        alignItems: 'center',
        marginTop: 16,
    },
    rewardInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        borderRadius: 16,
        padding: 20,
        marginTop: 32,
        borderWidth: 1,
    },
});

export const createWalletStyles = (theme: ThemeColors) => StyleSheet.create({
    balanceCardRedesign: {
        borderRadius: 32,
        padding: 32,
        marginTop: 16,
        overflow: 'hidden',
        position: 'relative',
        minHeight: 240,
        justifyContent: 'center',
    },
    balanceLabelRedesign: {
        fontSize: 12,
        fontWeight: '800',
        color: 'rgba(255,255,255,0.7)',
        letterSpacing: 2,
        marginBottom: 8,
    },
    balanceValueRedesign: {
        fontSize: 48,
        fontWeight: '700',
        color: '#fff',
        marginBottom: 32,
    },
    balanceActionsRedesign: {
        flexDirection: 'row',
        gap: 12,
    },
    withdrawButtonRedesign: {
        backgroundColor: '#fff',
        borderRadius: 16,
        paddingVertical: 18,
        paddingHorizontal: 40,
        flex: 1,
        alignItems: 'center',
    },
    withdrawTextRedesign: {
        fontSize: 14,
        fontWeight: '900',
        color: '#000',
        letterSpacing: 2,
    },
    addFundsButtonRedesign: {
        backgroundColor: 'rgba(255,255,255,0.2)',
        width: 56,
        height: 56,
        borderRadius: 16,
        justifyContent: 'center',
        alignItems: 'center',
    },
    cardIconRedesign: {
        position: 'absolute',
        top: 20,
        right: -20,
        opacity: 0.15,
    },
    historyTitleRedesign: {
        fontSize: 12,
        fontWeight: '900',
        color: theme.textSecondary,
        letterSpacing: 2,
        marginTop: 40,
        marginBottom: 20,
    },
    historyItemRedesign: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: theme.surface,
        borderRadius: 24,
        padding: 20,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: theme.border,
    },
    historyIconBoxRedesign: {
        width: 44,
        height: 44,
        borderRadius: 12,
        backgroundColor: 'rgba(19, 73, 236, 0.1)',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 16,
    },
    historyInfoRedesign: {
        flex: 1,
    },
    historyTitleTextRedesign: {
        fontSize: 13,
        fontWeight: '800',
        color: theme.text,
        marginBottom: 4,
    },
    historyDateRedesign: {
        fontSize: 10,
        color: theme.textSecondary,
        fontWeight: '800',
    },
    historyAmountRedesign: {
        fontSize: 16,
        fontWeight: '900',
    },
});

export const createModalStyles = (theme: ThemeColors) => StyleSheet.create({
    overlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.85)',
        justifyContent: 'flex-end',
    },
    container: {
        backgroundColor: theme.background,
        borderTopLeftRadius: 36,
        borderTopRightRadius: 36,
        paddingHorizontal: 24,
        paddingBottom: 48,
    },
    dragHandle: {
        width: 48,
        height: 5,
        backgroundColor: theme.border,
        borderRadius: 3,
        alignSelf: 'center',
        marginVertical: 16,
    },
    header: {
        marginBottom: 24,
    },
    title: {
        fontSize: 22,
        fontWeight: '900',
        color: theme.text,
        letterSpacing: 1,
        marginBottom: 6,
    },
    subtitle: {
        fontSize: 14,
        fontWeight: '500',
        color: theme.textSecondary,
    },
});

export const createSettingsStyles = (theme: ThemeColors) => StyleSheet.create({
    section: {
        marginBottom: 24,
    },
    sectionTitle: {
        fontSize: 12,
        fontWeight: '900',
        color: theme.primary,
        letterSpacing: 1.5,
        marginBottom: 12,
        marginLeft: 4,
    },
    item: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: 16,
        borderRadius: 20,
        marginBottom: 8,
        borderWidth: 1,
    },
    itemLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    iconBox: {
        width: 36,
        height: 36,
        borderRadius: 10,
        justifyContent: 'center',
        alignItems: 'center',
    },
    itemLabel: {
        fontSize: 15,
        fontWeight: '600',
        color: theme.text,
    },
    itemRight: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    itemValue: {
        fontSize: 13,
        color: theme.textSecondary,
    },
    logoutButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        padding: 18,
        borderRadius: 20,
        borderWidth: 1,
        marginTop: 12,
        gap: 8,
    },
    logoutText: {
        fontSize: 15,
        fontWeight: '800',
    },
    footerText: {
        textAlign: 'center',
        fontSize: 11,
        color: theme.textSecondary,
        marginTop: 32,
        marginBottom: 40,
        opacity: 0.5,
    },
});
